### ISSUE TITLE
Are we actually using Finalized/?

### ISSUE THREAD

**Issue by kWhittington** [UNO-CSCI-4675/honest_abe_audio#1]
Is Finalized/ going to be used or should we remove it from the repo? I'd like to go through the repo and clean it up some.

**Comment by CToups** [comment]
So, David is taking the somewhat uncommon approach of mastering his songs as he goes. So for him, finalized isn't actually necessary at all. 

I am leaving _some_ of my SFX un-effected. Some of those will probably remain that way, as say, footsteps, probably won't be bettered by any effects. Some however will be effected, and are not yet because I was thinking there would be some kind of feedback mechanism from the devs / designers / lead artist regarding the created SFX and things people might want changed in certain ways.

With all that said though, the way things have been going is not that way. So in the end, it's probably ok to delete the Finalized folder. I know I said a lot just to end with that, but in the interest of full transparency and understanding I offer my thoughts thus far.

**Comment by ddimaggio** [comment]
I've only mastered the theme (and the quartet version) but I just planned on deleting and replacing files when I master them.
